export const BOTAO_CLICADO_REQUEST = 'BOTAO_CLICADO_REQUEST'
export const BOTAO_CLICADO_SUCCESS = 'BOTAO_CLICADO_SUCCESS'
export const BOTAO_CLICADO_FAILURED = 'BOTAO_CLICADO_FAILURED'

export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURED = 'LOGIN_FAILURED'

export const PERSIST_REHYDRATE = 'persist/REHYDRATE'
